# Generated by Django 6.0.3 on 2026-03-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_twofactorotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hostelownerprofile',
            name='room_types',
            field=models.ManyToManyField(blank=True, related_name='owner_profiles', to='accounts.roomtype'),
        ),
    ]
