# Generated by Django 6.0.3 on 2026-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_roomtype_hostelownerprofile_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_session_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
