# Generated by Django 6.0.3 on 2026-03-11 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_session_token_user_last_session_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kirinyaga Hostels', max_length=255)),
                ('admin_email', models.EmailField(default='admin@kirinyagahostels.com', max_length=254)),
                ('contact_phone', models.CharField(default='+254712345678', max_length=20)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('admin_max_attempts', models.IntegerField(default=3)),
                ('lockout_hours', models.IntegerField(default=1)),
                ('twofa_required', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('roommate_finder_enabled', models.BooleanField(default=True)),
                ('student_reviews_enabled', models.BooleanField(default=True)),
                ('owner_chat_enabled', models.BooleanField(default=True)),
                ('subscriptions_enabled', models.BooleanField(default=True)),
                ('google_maps_enabled', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
