# Generated by Django 4.2.11 on 2026-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
