# Generated by Django 4.2.11 on 2026-04-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_avatar_user_avatar_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_category',
            field=models.CharField(choices=[('auth', 'Authentication'), ('hostel', 'Hostel Operation'), ('booking', 'Booking'), ('review', 'Review'), ('profile', 'Profile Update'), ('payment', 'Payment'), ('admin', 'Admin Action'), ('system', 'System'), ('view', 'View Action')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action_category'], name='accounts_au_user_id_503cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='accounts_au_resourc_30880d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='accounts_au_timesta_276167_idx'),
        ),
    ]
