# Generated by Django 6.0.4 on 2026-04-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fix_auditlog_ip_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_estimated_time',
            field=models.CharField(blank=True, default='', help_text='Estimated time (e.g., "30 minutes", "2 hours")', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='', help_text='Message to show during maintenance'),
        ),
    ]
