# Generated by Django 6.0.4 on 2026-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_systemsettings_maintenance_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
