# Generated by Django 6.0.4 on 2026-04-15 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersubscription',
            name='bonus_weeks',
            field=models.IntegerField(blank=True, help_text='Number of weeks granted as bonus', null=True),
        ),
        migrations.AddField(
            model_name='ownersubscription',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='Whether this is a free bonus subscription'),
        ),
        migrations.AddField(
            model_name='ownersubscription',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownersubscription',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
