# Generated by Django 6.0.3 on 2026-03-14 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_remove_booking_commission_paid_and_more'),
        ('hostels', '0022_alter_savedhostel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_hostel__6dbaec_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='move_in_date',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hostel', 'move_in_date'], name='bookings_bo_hostel__071a85_idx'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
