# Generated by Django 6.0.4 on 2026-04-11 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_bookings_bo_hostel__6dbaec_idx_and_more'),
        ('hostels', '0022_alter_savedhostel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('student', 'hostel', 'status')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['expires_at'], name='bookings_bo_expires_32f0a3_idx'),
        ),
    ]
