# Generated by Django 6.0.3 on 2026-03-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='other_amenities',
            field=models.TextField(blank=True, help_text='Other amenities not in the list, separated by commas'),
        ),
    ]
