# Generated by Django 6.0.3 on 2026-03-12 06:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_hostel_other_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hostelamenity',
            options={'ordering': ['amenity__category', 'amenity__name']},
        ),
        migrations.AlterModelOptions(
            name='hostelimage',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='savedhostel',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('furniture', 'Furniture'), ('utility', 'Utilities'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('outdoor', 'Outdoor')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times the hostel has been viewed'),
        ),
        migrations.AddField(
            model_name='hostelamenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Number of people the room can accommodate'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='room_type',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single', 'Single Room'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('studio', 'Studio Apartment'), ('shared', 'Shared Room')], default='bedsitter', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostelamenity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savedhostel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='hostelamenity',
            unique_together={('hostel', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['owner', 'is_approved'], name='hostels_hos_owner_i_a65dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_approved', 'available'], name='hostels_hos_is_appr_e53333_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_featured'], name='hostels_hos_is_feat_a5c963_idx'),
        ),
        migrations.AddField(
            model_name='hostelreview',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_reviews', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='hostelreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hostelreview',
            unique_together={('hostel', 'user')},
        ),
    ]
