# Generated by Django 6.0.3 on 2026-03-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostelreview_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='created_at',
        ),
    ]
