# Generated by Django 6.0.3 on 2026-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_remove_amenity_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='hostelamenity',
            options={'ordering': ['amenity__name']},
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='category',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
