# Generated by Django 6.0.3 on 2026-03-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_add_hostelimage_description_manual'),
    ]

    operations = [
    ]
