# Generated by Django 6.0.3 on 2026-03-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_add_hostelimage_description_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelimage',
            name='description',
        ),
    ]
