# Generated by Django 6.0.3 on 2026-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0009_temp_remove_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
