# Generated by Django 6.0.3 on 2026-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0012_add_created_at_to_hostelamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
    ]
