# Generated by Django 6.0.3 on 2026-03-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0013_alter_hostelamenity_created_at_and_more'),
        ('hostels', '0014_add_image_url'),
    ]

    operations = [
    ]
