# Generated by Django 6.0.3 on 2026-03-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0015_merge_20260312_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
