# Generated by Django 6.0.3 on 2026-03-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0016_alter_hostelimage_id'),
        ('hostels', '0017_add_hostelreview_table'),
    ]

    operations = [
    ]
