# Generated by Django 6.0.3 on 2026-03-13 14:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0018_merge_20260313_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
