# Generated by Django 6.0.3 on 2026-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0019_remove_hostelimage_image_url_alter_hostelimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelamenity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
