# Generated by Django 6.0.3 on 2026-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0020_alter_hostelamenity_id'),
    ]

    operations = [
        # No operations – the model change is already reflected in the database.
    ]