# Generated by Django 6.0.3 on 2026-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0021_alter_savedhostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedhostel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
