# Generated by Django 6.0.3 on 2026-03-06 03:57

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single', 'Single Room'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('other', 'Other')], default='bedsitter', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='roommate_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='roommate_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='roommate_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='roommate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reported_count', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='roommate_ads', to='hostels.amenity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='roommate.roommatead')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
