# Generated by Django 6.0.3 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('bulk', 'Bulk Notification'), ('owner_approved', 'Owner Approved'), ('hostel_approved', 'Hostel Approved'), ('hostel_rejected', 'Hostel Rejected'), ('booking', 'Booking'), ('payment', 'Payment'), ('alert', 'Alert')], default='bulk', max_length=20),
        ),
    ]
