# Generated by Django 4.2.11 on 2026-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_newslettersubscriber_announcement_emaillog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='notification_id',
            new_name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('bulk', 'Bulk Notification'), ('owner_approved', 'Owner Approved'), ('hostel_approved', 'Hostel Approved'), ('hostel_rejected', 'Hostel Rejected'), ('booking', 'Booking'), ('payment', 'Payment'), ('alert', 'Alert'), ('account_status', 'Account Status'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'user'], name='notificatio_is_read_d5146f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delete_at'], name='notificatio_delete__11ef60_idx'),
        ),
    ]
